apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-api
  description: "API de ejemplo para mi dev portal"
  tags: [api, backend]
spec:
  type: openapi
  lifecycle: production
  owner: ipadmins
  definition: |
    openapi: 3.0.0
    info:
      title: "My API"
      version: "1.0.0"
    paths:
      /users:
        get:
          summary: "Obtiene la lista de usuarios"
          responses:
            '200':
              description: "Lista de usuarios"
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: integer }
                        name: { type: string }
                        email: { type: string }
      /users/{userId}:
        get:
          summary: "Obtiene un usuario por su ID"
          parameters:
            - in: path
              name: userId
              required: true
              schema: { type: integer }
          responses:
            '200':
              description: "Detalles del usuario"
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      id: { type: integer }
                      name: { type: string }
                      email: { type: string }
